### ISSUE TITLE
Folder/file doesn't appear

### ISSUE THREAD

**Issue by dankastur** [bajrangCoder/PathIntellisense#4]
I have installed the plugin, but when I type ../ or ./ a list of existing folders/files doesn't appear

![Screenshot_2024-04-06-21-17-40-20_e3c1f266f17b29c7b40472751f031275.jpg](https://github.com/bajrangCoder/PathIntellisense/assets/96367567/d29834ec-7279-42b2-80bf-f6f2afa873a9)

![Screenshot_2024-04-06-21-17-27-77_e3c1f266f17b29c7b40472751f031275.jpg](https://github.com/bajrangCoder/PathIntellisense/assets/96367567/a61f7702-dd83-4d0e-be5c-593717e101e5)

https://github.com/bajrangCoder/PathIntellisense/assets/96367567/13c3f225-d1b2-4431-9673-239871a7187b

**Comment by bajrangCoder** [comment]
Seems something wrong 
If you can then share your project folder structure or path of your current opened file and logs which you can get using eruda Console plugin or any dev plugins

**Comment by ZidaneDanz** [comment]
> Seems something wrong 
> If you can then share your project folder structure or path of your current opened file and logs which you can get using eruda Console plugin or any dev plugins 

Uploading Record_2024-04-07-19-19-10.mp4 …

**Comment by ZidaneDanz** [comment]
> > Seems something wrong 
> > If you can then share your project folder structure or path of your current opened file and logs which you can get using eruda Console plugin or any dev plugins 
> 
> Uploading Record_2024-04-07-19-19-10.mp4 …

**Comment by dankastur** [comment]
I don't know why when I upload a video on GitHub it always loads, so I uploaded the video to Instagram 

[video](https://www.instagram.com/reel/C5deABlxR9t/?igsh=ZDA2bGZjeWd4NGs5)

**Comment by bajrangCoder** [comment]
Ok , no problem!
Really hard to find the problem because it's works fine for me .
Are you using any language client or LSP plugin? If yes then that can override path intelligence autocompletions

**Comment by dankastur** [comment]
> Ok , no problem!
> Really hard to find the problem because it's works fine for me .
> Are you using any language client or LSP plugin? If yes then that can override path intelligence autocompletions

How to override? I don't know what LSP plugins or language clients are, so I'll leave the plugins that I often use ![Screenshot_2024-04-08-02-03-25-47_e3c1f266f17b29c7b40472751f031275.jpg](https://github.com/bajrangCoder/PathIntellisense/assets/96367567/0effdb17-cd97-4c19-8ef9-016512f4658d)

**Comment by bajrangCoder** [comment]
> I have installed the plugin, but when I type ../ or ./ a list of existing folders/files doesn't appear
> 
> ![Screenshot_2024-04-06-21-17-40-20_e3c1f266f17b29c7b40472751f031275.jpg](https://private-user-images.githubusercontent.com/96367567/320211986-d29834ec-7279-42b2-80bf-f6f2afa873a9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1Mzg2MTIsIm5iZiI6MTcxMjUzODMxMiwicGF0aCI6Ii85NjM2NzU2Ny8zMjAyMTE5ODYtZDI5ODM0ZWMtNzI3OS00MmIyLTgwYmYtZjZmMmFmYTg3M2E5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAxMDUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNWYwZTQ5YjRhYmZlYjM5MTI3ODQ3ODI1OTBkMGI3OTkzYzU4YWM3ODU2OGE4YWY2YzdmYTVkYTM4NjNmOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LlcGMaB_w9tlOMxPuGPr36ttso3HAu8H7gT-0mmMz5I)
> 
> ![Screenshot_2024-04-06-21-17-27-77_e3c1f266f17b29c7b40472751f031275.jpg](https://private-user-images.githubusercontent.com/96367567/320211989-a61f7702-dd83-4d0e-be5c-593717e101e5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1Mzg2MTIsIm5iZiI6MTcxMjUzODMxMiwicGF0aCI6Ii85NjM2NzU2Ny8zMjAyMTE5ODktYTYxZjc3MDItZGQ4My00ZDBlLWJlNWMtNTkzNzE3ZTEwMWU1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAxMDUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjOGI0YTBiZjA2M2ZkOTQ4MTNiYjlkNjBhMGNmZDQwMzNiZmZmNzkyZTZjNTEzYWRhYTBkMTI5MDMzMWIzZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JswHBbNWW342AQ5MmkPMP2eXSwDuNl_8-Nz7WKlM_mQ)
> 
>  Record_2024-04-06-21-14-53.mp4

But here in this video you have Acode Language Server (Beta) or Acode Language client just change its one settings and restart Acode (because they just remove the suggestions of other plugin by default)

Change : `Replace Completer`

**Comment by dankastur** [comment]
> > I have installed the plugin, but when I type ../ or ./ a list of existing folders/files doesn't appear
> > 
> > ![Screenshot_2024-04-06-21-17-40-20_e3c1f266f17b29c7b40472751f031275.jpg](https://private-user-images.githubusercontent.com/96367567/320211986-d29834ec-7279-42b2-80bf-f6f2afa873a9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1Mzg2MTIsIm5iZiI6MTcxMjUzODMxMiwicGF0aCI6Ii85NjM2NzU2Ny8zMjAyMTE5ODYtZDI5ODM0ZWMtNzI3OS00MmIyLTgwYmYtZjZmMmFmYTg3M2E5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAxMDUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNWYwZTQ5YjRhYmZlYjM5MTI3ODQ3ODI1OTBkMGI3OTkzYzU4YWM3ODU2OGE4YWY2YzdmYTVkYTM4NjNmOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LlcGMaB_w9tlOMxPuGPr36ttso3HAu8H7gT-0mmMz5I)
> > 
> > ![Screenshot_2024-04-06-21-17-27-77_e3c1f266f17b29c7b40472751f031275.jpg](https://private-user-images.githubusercontent.com/96367567/320211989-a61f7702-dd83-4d0e-be5c-593717e101e5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1Mzg2MTIsIm5iZiI6MTcxMjUzODMxMiwicGF0aCI6Ii85NjM2NzU2Ny8zMjAyMTE5ODktYTYxZjc3MDItZGQ4My00ZDBlLWJlNWMtNTkzNzE3ZTEwMWU1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAxMDUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjOGI0YTBiZjA2M2ZkOTQ4MTNiYjlkNjBhMGNmZDQwMzNiZmZmNzkyZTZjNTEzYWRhYTBkMTI5MDMzMWIzZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JswHBbNWW342AQ5MmkPMP2eXSwDuNl_8-Nz7WKlM_mQ)
> > 
> >  Record_2024-04-06-21-14-53.mp4
> 
> But here in this video you have Acode Language Server (Beta) or Acode Language client just change its one settings and restart Acode (because they just remove the suggestions of other plugin by default)
> 
> Change : `Replace Completer`

I uninstalled all the plugins that I rarely use because I don't know what language the client is. I haven't tried again after uninstalling, it's already morning here and I haven't slept yet, After I wake up I will test again

**Comment by dankastur** [comment]
After leaving only 4 plugins that I often use, a list of files and folders now appears

**Comment by bajrangCoder** [comment]
Actually the LSP plugins are responsible for those stuff
